version: '3'
services:
  domain-service:
    build:
      context: .
      dockerfile: ./Dockerfile-domain
    ports:
      - "3001:8081"
  api-service:
    build:
      context: .
      dockerfile: ./Dockerfile-api
    ports:
      - "3000:8080"
    links:
      - domain-service
    environment:
      DOMAIN_URL: domain-service:8081