version: '2'
services:
  domain-service:
    build: ./domain-service
    ports:
      - "3001:8081"
  api-service:
    build: ./api-service
    ports:
      - "3000:8080"
    links:
      - domain-service
    environment:
      DOMAIN_URL: domain-service:8081