# Start from golang alpine
FROM golang:alpine AS builder

WORKDIR /go/src/github.com/sin-ivan/port-project/

COPY ./proto/ ./proto/

# Set the Current Working Directory inside the container
WORKDIR /go/src/github.com/sin-ivan/port-project/domain-service/

# Copy everything from the current directory to the working directory inside the container
COPY /domain-service/ .

RUN apk add --no-cache git

# # Download all the dependencies
RUN go get -d -v "google.golang.org/grpc"
RUN go get -d -v "github.com/golang/protobuf/proto"
RUN go get -d -v "gopkg.in/natefinch/lumberjack.v2"

# Install the package
RUN go install -v "gopkg.in/natefinch/lumberjack.v2"
RUN go install -v "google.golang.org/grpc"
RUN go install -v "github.com/golang/protobuf/proto"

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/domain-service .

######## Start a new stage from scratch #######
FROM alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /go/bin/domain-service .

EXPOSE 8080

CMD ["./domain-service"] 